### ISSUE TITLE
Treinamento PO UI

### ISSUE THREAD

**Issue by efdeiasoliveira** [deboraconstantino/universo_totvs24#1]
@deboraconstantino, após a apresentação você comentou comigo que tem um ou mais cursos de PO UI disponível na central de treinamento da Totvs. 

Eu dei uma pesquisada porém não encontrei. Teria como enviar o link ? 

Desde já agradeço

**Comment by deboraconstantino** [comment]
Boa tarde @efdeiasoliveira 
Você pode acessar por esse link: https://educacao.totvs.com/#/level/609871
Primeiro vai pedir seu login, aí depois você pode procurar por "Aplicações PO-UI" e selecionar o curso "Aplicações PO-UI e serviços REST no Protheus". Após isso, você precisa se matricular no curso e consegue ter o acesso.

Se você já tem um produto TOTVS, provavelmente você já tem o acesso à essa plataforma, você só precisa ligar no comercial e pedir pra liberar o acesso. Ou você pode contratar as licenças que darão acesso de forma anual ou de 60 dias.

**Comment by efdeiasoliveira** [comment]
Ok.. Perfeito, segui as suas instruções e consegui acesso.

Muito obrigado !...

**Comment by efdeiasoliveira** [comment]
Ok.. Perfeito, segui as suas instruções e consegui acesso.

Muito obrigado !...

**Comment by deboraconstantino** [comment]
Que bom @efdeiasoliveira !
Qualquer dúvida pode me dar um toque por aqui :D
